/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://afzh2kjmkfhrvb7aavqvfcntpa.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fdqbjlvpqrgcteuohnpgoi4qrq",
    "aws_cognito_identity_pool_id": "us-east-1:e6839dcd-2b40-459e-bbe3-d12ce56f41ce",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_qnd5aoW8j",
    "aws_user_pools_web_client_id": "aq8snekhmkddkol9uuuarvrgc",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "bizzi7a00d287161248519c73c9a72181116f135649-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
